-- Generated by design/ingestion/apply_province_panel.py - do not hand-edit.
-- Applies a provincial panel's returned decisions. Re-running is safe:
-- each run versions the affected profiles rather than mutating them in place.
BEGIN;

-- 0. the account the decisions are attributed to --------------------------
-- save_profile_weights() records decided_by for every contested or rejected
-- membership. An exclusion that cannot be attributed is indistinguishable
-- from an oversight (SRS 2.4), so a NULL user here is not acceptable: this
-- creates a suspended service account that no one can sign in as, whose only
-- purpose is to carry the attribution for decisions loaded from a file.
INSERT INTO app_user (email, password_hash, full_name, organization,
                      is_active, status)
VALUES ('panel-import@riskradar.local', '!no-login', 'Provincial panel import',
        'Risk Radar system account', FALSE, 'suspended')
ON CONFLICT (email) DO NOTHING;

-- 1. the panel's new variables ------------------------------------------
INSERT INTO indicator_catalog
    (code, name, domain, direction, norm_method, norm_scope,
     period_aggregation, is_composite_index, status, value_kind,
     description)
SELECT 'DROUGHT_EVENTS_1974_TO_2004', 'No. of Drought events - 1974 to 2004 (25%)', 'hazard'::domain_type,
       ic.direction, ic.norm_method, ic.norm_scope,
       ic.period_aggregation, FALSE, 'active',
       'absolute'::indicator_value_kind, 'added to the data tab during the Central review; not yet in FINAL_VARIABLES.xlsx | settings inherited from DROUGHT_EVENTS_1974_TO_2022'
  FROM indicator_catalog ic WHERE ic.code = 'DROUGHT_EVENTS_1974_TO_2022'
ON CONFLICT (code) DO NOTHING;

INSERT INTO indicator_catalog
    (code, name, domain, direction, norm_method, norm_scope,
     period_aggregation, is_composite_index, status, value_kind,
     description)
SELECT 'DROUGHT_EVENTS_2005_TO_2022', 'No. of Drought events - 2005 -2022 (75%)', 'hazard'::domain_type,
       ic.direction, ic.norm_method, ic.norm_scope,
       ic.period_aggregation, FALSE, 'active',
       'absolute'::indicator_value_kind, 'added to the data tab during the Central review; not yet in FINAL_VARIABLES.xlsx | settings inherited from DROUGHT_EVENTS_1974_TO_2022'
  FROM indicator_catalog ic WHERE ic.code = 'DROUGHT_EVENTS_1974_TO_2022'
ON CONFLICT (code) DO NOTHING;

INSERT INTO indicator_catalog
    (code, name, domain, direction, norm_method, norm_scope,
     period_aggregation, is_composite_index, status, value_kind,
     description)
SELECT 'FLOOD_EVENTS_1974_TO_2004', 'No. of Flood events_ 1974-2004_25%', 'hazard'::domain_type,
       ic.direction, ic.norm_method, ic.norm_scope,
       ic.period_aggregation, FALSE, 'active',
       'absolute'::indicator_value_kind, 'added to the data tab during the Central review; not yet in FINAL_VARIABLES.xlsx | settings inherited from FLOOD_EVENTS_1974_TO_2023'
  FROM indicator_catalog ic WHERE ic.code = 'FLOOD_EVENTS_1974_TO_2023'
ON CONFLICT (code) DO NOTHING;

INSERT INTO indicator_catalog
    (code, name, domain, direction, norm_method, norm_scope,
     period_aggregation, is_composite_index, status, value_kind,
     description)
SELECT 'FLOOD_EVENTS_2005_TO_2023', 'No. of Flood events_ 2005-2023_75%', 'hazard'::domain_type,
       ic.direction, ic.norm_method, ic.norm_scope,
       ic.period_aggregation, FALSE, 'active',
       'absolute'::indicator_value_kind, 'added to the data tab during the Central review; not yet in FINAL_VARIABLES.xlsx | settings inherited from FLOOD_EVENTS_1974_TO_2023'
  FROM indicator_catalog ic WHERE ic.code = 'FLOOD_EVENTS_1974_TO_2023'
ON CONFLICT (code) DO NOTHING;

INSERT INTO indicator_catalog
    (code, name, domain, direction, norm_method, norm_scope,
     period_aggregation, is_composite_index, status, value_kind,
     description)
SELECT 'MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2004', 'Max # of drought affected People - 1974 to 2004 (25%)', 'exposure'::domain_type,
       ic.direction, ic.norm_method, ic.norm_scope,
       ic.period_aggregation, FALSE, 'active',
       'absolute'::indicator_value_kind, 'added to the data tab during the Central review; not yet in FINAL_VARIABLES.xlsx | settings inherited from MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022'
  FROM indicator_catalog ic WHERE ic.code = 'MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022'
ON CONFLICT (code) DO NOTHING;

INSERT INTO indicator_catalog
    (code, name, domain, direction, norm_method, norm_scope,
     period_aggregation, is_composite_index, status, value_kind,
     description)
SELECT 'MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_2005_TO_2022', 'Max # of drought affected People - 2005 to 2022 (75%)', 'exposure'::domain_type,
       ic.direction, ic.norm_method, ic.norm_scope,
       ic.period_aggregation, FALSE, 'active',
       'absolute'::indicator_value_kind, 'added to the data tab during the Central review; not yet in FINAL_VARIABLES.xlsx | settings inherited from MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022'
  FROM indicator_catalog ic WHERE ic.code = 'MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022'
ON CONFLICT (code) DO NOTHING;

INSERT INTO indicator_catalog
    (code, name, domain, direction, norm_method, norm_scope,
     period_aggregation, is_composite_index, status, value_kind,
     description)
SELECT 'MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2004', 'Max_affected_flood - 1974-2004-25%', 'exposure'::domain_type,
       ic.direction, ic.norm_method, ic.norm_scope,
       ic.period_aggregation, FALSE, 'active',
       'absolute'::indicator_value_kind, 'added to the data tab during the Central review; not yet in FINAL_VARIABLES.xlsx | settings inherited from MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023'
  FROM indicator_catalog ic WHERE ic.code = 'MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023'
ON CONFLICT (code) DO NOTHING;

INSERT INTO indicator_catalog
    (code, name, domain, direction, norm_method, norm_scope,
     period_aggregation, is_composite_index, status, value_kind,
     description)
SELECT 'MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_2005_TO_2023', 'Max_affected_flood-2005-2023-75%', 'exposure'::domain_type,
       ic.direction, ic.norm_method, ic.norm_scope,
       ic.period_aggregation, FALSE, 'active',
       'absolute'::indicator_value_kind, 'added to the data tab during the Central review; not yet in FINAL_VARIABLES.xlsx | settings inherited from MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023'
  FROM indicator_catalog ic WHERE ic.code = 'MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023'
ON CONFLICT (code) DO NOTHING;

INSERT INTO indicator_catalog
    (code, name, domain, direction, norm_method, norm_scope,
     period_aggregation, is_composite_index, status, value_kind,
     description)
SELECT 'THREE_DAY_CUMULATIVE_RAINFALL', '3 day cumulative rain fall', 'hazard'::domain_type,
       ic.direction, ic.norm_method, ic.norm_scope,
       ic.period_aggregation, FALSE, 'active',
       'signed'::indicator_value_kind, 'added to the data tab during the Central review; not yet in FINAL_VARIABLES.xlsx; the panel''s own column header was ''3DAY_CUMULATIVE_RAINFALL'' - keep that as an indicator_alias so their returned files still match | settings inherited from VERY_WET_DAYS'
  FROM indicator_catalog ic WHERE ic.code = 'VERY_WET_DAYS'
ON CONFLICT (code) DO NOTHING;
UPDATE indicator_catalog SET value_kind = 'signed'
 WHERE code = 'THREE_DAY_CUMULATIVE_RAINFALL' AND value_kind <> 'signed';

INSERT INTO indicator_catalog
    (code, name, domain, direction, norm_method, norm_scope,
     period_aggregation, is_composite_index, status, value_kind,
     description)
SELECT 'VERY_WET_DAYS_95TH_PERCENTILE', 'Very wet days (95th percentile)', 'hazard'::domain_type,
       ic.direction, ic.norm_method, ic.norm_scope,
       ic.period_aggregation, FALSE, 'active',
       'absolute'::indicator_value_kind, 'added to the data tab during the Central review; not yet in FINAL_VARIABLES.xlsx | settings inherited from VERY_WET_DAYS'
  FROM indicator_catalog ic WHERE ic.code = 'VERY_WET_DAYS'
ON CONFLICT (code) DO NOTHING;

-- 1b. header aliases -------------------------------------------------------
-- The heading the panel actually typed, kept so their returned workbooks and
-- anything else written against that heading still resolve after a rename.
INSERT INTO indicator_alias (indicator_id, alias)
SELECT id, '3DAY_CUMULATIVE_RAINFALL' FROM indicator_catalog WHERE code = 'THREE_DAY_CUMULATIVE_RAINFALL'
ON CONFLICT DO NOTHING;

-- 2. the panel's decisions, scope by scope --------------------------------
CREATE TEMP TABLE panel_override (
    province text, sector text, subsector text, hazard text,
    code text, action text, weight_pct numeric, basis text, note text
) ON COMMIT DROP;
INSERT INTO panel_override VALUES
  ('Sabaragamuwa', 'Livestock Sector', 'Buffalo Farming', 'Drought', 'DROUGHT_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Livestock Sector', 'Buffalo Farming', 'Drought', 'DROUGHT_EVENTS_2005_TO_2022', 'add', 37.5, 'derived: 75% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Livestock Sector', 'Buffalo Farming', 'Drought', 'DROUGHT_EVENTS_1974_TO_2022', 'retire', NULL, NULL, 'superseded by DROUGHT_EVENTS_1974_TO_2004 + DROUGHT_EVENTS_2005_TO_2022'),
  ('Sabaragamuwa', 'Livestock Sector', 'Buffalo Farming', 'Flood', 'FLOOD_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Livestock Sector', 'Buffalo Farming', 'Flood', 'FLOOD_EVENTS_2005_TO_2023', 'add', 37.5, 'derived: 75% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Livestock Sector', 'Buffalo Farming', 'Flood', 'FLOOD_EVENTS_1974_TO_2023', 'retire', NULL, NULL, 'superseded by FLOOD_EVENTS_1974_TO_2004 + FLOOD_EVENTS_2005_TO_2023'),
  ('Sabaragamuwa', 'Livestock Sector', 'Buffalo Farming', 'Flood', 'THREE_DAY_CUMULATIVE_RAINFALL', 'add', 21, 'derived: 60% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Livestock Sector', 'Buffalo Farming', 'Flood', 'VERY_WET_DAYS_95TH_PERCENTILE', 'add', 14, 'derived: 40% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Livestock Sector', 'Buffalo Farming', 'Flood', 'VERY_WET_DAYS', 'retire', NULL, NULL, 'superseded by THREE_DAY_CUMULATIVE_RAINFALL + VERY_WET_DAYS_95TH_PERCENTILE'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Coconut', 'Drought', 'DROUGHT_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Coconut', 'Drought', 'DROUGHT_EVENTS_2005_TO_2022', 'add', 37.5, 'derived: 75% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Coconut', 'Drought', 'DROUGHT_EVENTS_1974_TO_2022', 'retire', NULL, NULL, 'superseded by DROUGHT_EVENTS_1974_TO_2004 + DROUGHT_EVENTS_2005_TO_2022'),
  ('Sabaragamuwa', 'Livestock Sector', 'Goat Farming', 'Drought', 'DROUGHT_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Livestock Sector', 'Goat Farming', 'Drought', 'DROUGHT_EVENTS_2005_TO_2022', 'add', 37.5, 'derived: 75% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Livestock Sector', 'Goat Farming', 'Drought', 'DROUGHT_EVENTS_1974_TO_2022', 'retire', NULL, NULL, 'superseded by DROUGHT_EVENTS_1974_TO_2004 + DROUGHT_EVENTS_2005_TO_2022'),
  ('Sabaragamuwa', 'Livestock Sector', 'Goat Farming', 'Flood', 'FLOOD_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Livestock Sector', 'Goat Farming', 'Flood', 'FLOOD_EVENTS_2005_TO_2023', 'add', 37.5, 'derived: 75% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Livestock Sector', 'Goat Farming', 'Flood', 'FLOOD_EVENTS_1974_TO_2023', 'retire', NULL, NULL, 'superseded by FLOOD_EVENTS_1974_TO_2004 + FLOOD_EVENTS_2005_TO_2023'),
  ('Sabaragamuwa', 'Livestock Sector', 'Goat Farming', 'Flood', 'THREE_DAY_CUMULATIVE_RAINFALL', 'add', 21, 'derived: 60% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Livestock Sector', 'Goat Farming', 'Flood', 'VERY_WET_DAYS_95TH_PERCENTILE', 'add', 14, 'derived: 40% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Livestock Sector', 'Goat Farming', 'Flood', 'VERY_WET_DAYS', 'retire', NULL, NULL, 'superseded by THREE_DAY_CUMULATIVE_RAINFALL + VERY_WET_DAYS_95TH_PERCENTILE'),
  ('Sabaragamuwa', 'Human Settlements Sector', NULL, 'Drought', 'DROUGHT_EVENTS_1974_TO_2004', 'add', 10, 'derived: 25% of retired DROUGHT_EVENTS_1974_TO_2022 (40)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Human Settlements Sector', NULL, 'Drought', 'DROUGHT_EVENTS_2005_TO_2022', 'add', 30, 'derived: 75% of retired DROUGHT_EVENTS_1974_TO_2022 (40)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Human Settlements Sector', NULL, 'Drought', 'DROUGHT_EVENTS_1974_TO_2022', 'retire', NULL, NULL, 'superseded by DROUGHT_EVENTS_1974_TO_2004 + DROUGHT_EVENTS_2005_TO_2022'),
  ('Sabaragamuwa', 'Human Settlements Sector', NULL, 'Drought', 'MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2004', 'add', 6.25, 'derived: 25% of retired MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022 (25)', 'replaces MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022'),
  ('Sabaragamuwa', 'Human Settlements Sector', NULL, 'Drought', 'MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_2005_TO_2022', 'add', 18.75, 'derived: 75% of retired MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022 (25)', 'replaces MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022'),
  ('Sabaragamuwa', 'Human Settlements Sector', NULL, 'Drought', 'MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022', 'retire', NULL, NULL, 'superseded by MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2004 + MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_2005_TO_2022'),
  ('Sabaragamuwa', 'Human Settlements Sector', NULL, 'Flood', 'FLOOD_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Human Settlements Sector', NULL, 'Flood', 'FLOOD_EVENTS_2005_TO_2023', 'add', 37.5, 'derived: 75% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Human Settlements Sector', NULL, 'Flood', 'FLOOD_EVENTS_1974_TO_2023', 'retire', NULL, NULL, 'superseded by FLOOD_EVENTS_1974_TO_2004 + FLOOD_EVENTS_2005_TO_2023'),
  ('Sabaragamuwa', 'Human Settlements Sector', NULL, 'Flood', 'MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2004', 'add', 8.75, 'derived: 25% of retired MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023 (35)', 'replaces MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023'),
  ('Sabaragamuwa', 'Human Settlements Sector', NULL, 'Flood', 'MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_2005_TO_2023', 'add', 26.25, 'derived: 75% of retired MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023 (35)', 'replaces MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023'),
  ('Sabaragamuwa', 'Human Settlements Sector', NULL, 'Flood', 'MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023', 'retire', NULL, NULL, 'superseded by MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2004 + MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_2005_TO_2023'),
  ('Sabaragamuwa', 'Human Settlements Sector', NULL, 'Flood', 'THREE_DAY_CUMULATIVE_RAINFALL', 'add', 21, 'derived: 60% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Human Settlements Sector', NULL, 'Flood', 'VERY_WET_DAYS_95TH_PERCENTILE', 'add', 14, 'derived: 40% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Human Settlements Sector', NULL, 'Flood', 'VERY_WET_DAYS', 'retire', NULL, NULL, 'superseded by THREE_DAY_CUMULATIVE_RAINFALL + VERY_WET_DAYS_95TH_PERCENTILE'),
  ('Sabaragamuwa', 'Industry Sector', NULL, 'Drought', 'DROUGHT_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Industry Sector', NULL, 'Drought', 'DROUGHT_EVENTS_2005_TO_2022', 'add', 37.5, 'derived: 75% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Industry Sector', NULL, 'Drought', 'DROUGHT_EVENTS_1974_TO_2022', 'retire', NULL, NULL, 'superseded by DROUGHT_EVENTS_1974_TO_2004 + DROUGHT_EVENTS_2005_TO_2022'),
  ('Sabaragamuwa', 'Industry Sector', NULL, 'Drought', 'MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2004', 'add', 2.5, 'derived: 25% of retired MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022 (10)', 'replaces MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022'),
  ('Sabaragamuwa', 'Industry Sector', NULL, 'Drought', 'MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_2005_TO_2022', 'add', 7.5, 'derived: 75% of retired MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022 (10)', 'replaces MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022'),
  ('Sabaragamuwa', 'Industry Sector', NULL, 'Drought', 'MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022', 'retire', NULL, NULL, 'superseded by MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2004 + MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_2005_TO_2022'),
  ('Sabaragamuwa', 'Industry Sector', NULL, 'Flood', 'FLOOD_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Industry Sector', NULL, 'Flood', 'FLOOD_EVENTS_2005_TO_2023', 'add', 37.5, 'derived: 75% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Industry Sector', NULL, 'Flood', 'FLOOD_EVENTS_1974_TO_2023', 'retire', NULL, NULL, 'superseded by FLOOD_EVENTS_1974_TO_2004 + FLOOD_EVENTS_2005_TO_2023'),
  ('Sabaragamuwa', 'Industry Sector', NULL, 'Flood', 'MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2004', 'add', 2.5, 'derived: 25% of retired MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023 (10)', 'replaces MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023'),
  ('Sabaragamuwa', 'Industry Sector', NULL, 'Flood', 'MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_2005_TO_2023', 'add', 7.5, 'derived: 75% of retired MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023 (10)', 'replaces MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023'),
  ('Sabaragamuwa', 'Industry Sector', NULL, 'Flood', 'MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023', 'retire', NULL, NULL, 'superseded by MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2004 + MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_2005_TO_2023'),
  ('Sabaragamuwa', 'Industry Sector', NULL, 'Flood', 'THREE_DAY_CUMULATIVE_RAINFALL', 'add', 21, 'derived: 60% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Industry Sector', NULL, 'Flood', 'VERY_WET_DAYS_95TH_PERCENTILE', 'add', 14, 'derived: 40% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Industry Sector', NULL, 'Flood', 'VERY_WET_DAYS', 'retire', NULL, NULL, 'superseded by THREE_DAY_CUMULATIVE_RAINFALL + VERY_WET_DAYS_95TH_PERCENTILE'),
  ('Sabaragamuwa', 'Water Sector', 'Irrigation Water', 'Drought', 'DROUGHT_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Water Sector', 'Irrigation Water', 'Drought', 'DROUGHT_EVENTS_2005_TO_2022', 'add', 37.5, 'derived: 75% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Water Sector', 'Irrigation Water', 'Drought', 'DROUGHT_EVENTS_1974_TO_2022', 'retire', NULL, NULL, 'superseded by DROUGHT_EVENTS_1974_TO_2004 + DROUGHT_EVENTS_2005_TO_2022'),
  ('Sabaragamuwa', 'Water Sector', 'Irrigation Water', 'Drought', 'MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2004', 'add', 7.5, 'derived: 25% of retired MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022 (30)', 'replaces MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022'),
  ('Sabaragamuwa', 'Water Sector', 'Irrigation Water', 'Drought', 'MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_2005_TO_2022', 'add', 22.5, 'derived: 75% of retired MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022 (30)', 'replaces MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022'),
  ('Sabaragamuwa', 'Water Sector', 'Irrigation Water', 'Drought', 'MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022', 'retire', NULL, NULL, 'superseded by MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2004 + MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_2005_TO_2022'),
  ('Sabaragamuwa', 'Water Sector', 'Irrigation Water', 'Flood', 'FLOOD_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Water Sector', 'Irrigation Water', 'Flood', 'FLOOD_EVENTS_2005_TO_2023', 'add', 37.5, 'derived: 75% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Water Sector', 'Irrigation Water', 'Flood', 'FLOOD_EVENTS_1974_TO_2023', 'retire', NULL, NULL, 'superseded by FLOOD_EVENTS_1974_TO_2004 + FLOOD_EVENTS_2005_TO_2023'),
  ('Sabaragamuwa', 'Water Sector', 'Irrigation Water', 'Flood', 'MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2004', 'add', 2.5, 'derived: 25% of retired MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023 (10)', 'replaces MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023'),
  ('Sabaragamuwa', 'Water Sector', 'Irrigation Water', 'Flood', 'MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_2005_TO_2023', 'add', 7.5, 'derived: 75% of retired MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023 (10)', 'replaces MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023'),
  ('Sabaragamuwa', 'Water Sector', 'Irrigation Water', 'Flood', 'MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2023', 'retire', NULL, NULL, 'superseded by MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_1974_TO_2004 + MAXIMUM_FLOOD_AFFECTED_PEOPLE_DURING_2005_TO_2023'),
  ('Sabaragamuwa', 'Water Sector', 'Irrigation Water', 'Flood', 'THREE_DAY_CUMULATIVE_RAINFALL', 'add', 21, 'derived: 60% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Water Sector', 'Irrigation Water', 'Flood', 'VERY_WET_DAYS_95TH_PERCENTILE', 'add', 14, 'derived: 40% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Water Sector', 'Irrigation Water', 'Flood', 'VERY_WET_DAYS', 'retire', NULL, NULL, 'superseded by THREE_DAY_CUMULATIVE_RAINFALL + VERY_WET_DAYS_95TH_PERCENTILE'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Paddy', 'Drought', 'DROUGHT_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Paddy', 'Drought', 'DROUGHT_EVENTS_2005_TO_2022', 'add', 37.5, 'derived: 75% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Paddy', 'Drought', 'DROUGHT_EVENTS_1974_TO_2022', 'retire', NULL, NULL, 'superseded by DROUGHT_EVENTS_1974_TO_2004 + DROUGHT_EVENTS_2005_TO_2022'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Paddy', 'Drought', 'MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2004', 'add', 5, 'derived: 25% of retired MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022 (20)', 'replaces MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Paddy', 'Drought', 'MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_2005_TO_2022', 'add', 15, 'derived: 75% of retired MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022 (20)', 'replaces MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Paddy', 'Drought', 'MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2022', 'retire', NULL, NULL, 'superseded by MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_1974_TO_2004 + MAXIMUM_DROUGHT_AFFECTED_PEOPLE_DURING_2005_TO_2022'),
  ('Sabaragamuwa', 'Livestock Sector', 'Pig and Sheep Farming', 'Drought', 'DROUGHT_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Livestock Sector', 'Pig and Sheep Farming', 'Drought', 'DROUGHT_EVENTS_2005_TO_2022', 'add', 37.5, 'derived: 75% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Livestock Sector', 'Pig and Sheep Farming', 'Drought', 'DROUGHT_EVENTS_1974_TO_2022', 'retire', NULL, NULL, 'superseded by DROUGHT_EVENTS_1974_TO_2004 + DROUGHT_EVENTS_2005_TO_2022'),
  ('Sabaragamuwa', 'Livestock Sector', 'Pig and Sheep Farming', 'Flood', 'FLOOD_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Livestock Sector', 'Pig and Sheep Farming', 'Flood', 'FLOOD_EVENTS_2005_TO_2023', 'add', 37.5, 'derived: 75% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Livestock Sector', 'Pig and Sheep Farming', 'Flood', 'FLOOD_EVENTS_1974_TO_2023', 'retire', NULL, NULL, 'superseded by FLOOD_EVENTS_1974_TO_2004 + FLOOD_EVENTS_2005_TO_2023'),
  ('Sabaragamuwa', 'Livestock Sector', 'Pig and Sheep Farming', 'Flood', 'THREE_DAY_CUMULATIVE_RAINFALL', 'add', 21, 'derived: 60% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Livestock Sector', 'Pig and Sheep Farming', 'Flood', 'VERY_WET_DAYS_95TH_PERCENTILE', 'add', 14, 'derived: 40% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Livestock Sector', 'Pig and Sheep Farming', 'Flood', 'VERY_WET_DAYS', 'retire', NULL, NULL, 'superseded by THREE_DAY_CUMULATIVE_RAINFALL + VERY_WET_DAYS_95TH_PERCENTILE'),
  ('Sabaragamuwa', 'Livestock Sector', 'Poultry Farming', 'Drought', 'DROUGHT_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Livestock Sector', 'Poultry Farming', 'Drought', 'DROUGHT_EVENTS_2005_TO_2022', 'add', 37.5, 'derived: 75% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Livestock Sector', 'Poultry Farming', 'Drought', 'DROUGHT_EVENTS_1974_TO_2022', 'retire', NULL, NULL, 'superseded by DROUGHT_EVENTS_1974_TO_2004 + DROUGHT_EVENTS_2005_TO_2022'),
  ('Sabaragamuwa', 'Livestock Sector', 'Poultry Farming', 'Flood', 'FLOOD_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Livestock Sector', 'Poultry Farming', 'Flood', 'FLOOD_EVENTS_2005_TO_2023', 'add', 37.5, 'derived: 75% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Livestock Sector', 'Poultry Farming', 'Flood', 'FLOOD_EVENTS_1974_TO_2023', 'retire', NULL, NULL, 'superseded by FLOOD_EVENTS_1974_TO_2004 + FLOOD_EVENTS_2005_TO_2023'),
  ('Sabaragamuwa', 'Livestock Sector', 'Poultry Farming', 'Flood', 'THREE_DAY_CUMULATIVE_RAINFALL', 'add', 21, 'derived: 60% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Livestock Sector', 'Poultry Farming', 'Flood', 'VERY_WET_DAYS_95TH_PERCENTILE', 'add', 14, 'derived: 40% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Livestock Sector', 'Poultry Farming', 'Flood', 'VERY_WET_DAYS', 'retire', NULL, NULL, 'superseded by THREE_DAY_CUMULATIVE_RAINFALL + VERY_WET_DAYS_95TH_PERCENTILE'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Tea', 'Drought', 'DROUGHT_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Tea', 'Drought', 'DROUGHT_EVENTS_2005_TO_2022', 'add', 37.5, 'derived: 75% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Tea', 'Drought', 'DROUGHT_EVENTS_1974_TO_2022', 'retire', NULL, NULL, 'superseded by DROUGHT_EVENTS_1974_TO_2004 + DROUGHT_EVENTS_2005_TO_2022'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Tea', 'Flood', 'FLOOD_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Tea', 'Flood', 'FLOOD_EVENTS_2005_TO_2023', 'add', 37.5, 'derived: 75% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Tea', 'Flood', 'FLOOD_EVENTS_1974_TO_2023', 'retire', NULL, NULL, 'superseded by FLOOD_EVENTS_1974_TO_2004 + FLOOD_EVENTS_2005_TO_2023'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Tea', 'Flood', 'THREE_DAY_CUMULATIVE_RAINFALL', 'add', 21, 'derived: 60% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Tea', 'Flood', 'VERY_WET_DAYS_95TH_PERCENTILE', 'add', 14, 'derived: 40% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Agriculture Sector', 'Tea', 'Flood', 'VERY_WET_DAYS', 'retire', NULL, NULL, 'superseded by THREE_DAY_CUMULATIVE_RAINFALL + VERY_WET_DAYS_95TH_PERCENTILE'),
  ('Sabaragamuwa', 'Tourism Sector', NULL, 'Drought', 'DROUGHT_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Tourism Sector', NULL, 'Drought', 'DROUGHT_EVENTS_2005_TO_2022', 'add', 37.5, 'derived: 75% of retired DROUGHT_EVENTS_1974_TO_2022 (50)', 'replaces DROUGHT_EVENTS_1974_TO_2022'),
  ('Sabaragamuwa', 'Tourism Sector', NULL, 'Drought', 'DROUGHT_EVENTS_1974_TO_2022', 'retire', NULL, NULL, 'superseded by DROUGHT_EVENTS_1974_TO_2004 + DROUGHT_EVENTS_2005_TO_2022'),
  ('Sabaragamuwa', 'Tourism Sector', NULL, 'Flood', 'FLOOD_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Tourism Sector', NULL, 'Flood', 'FLOOD_EVENTS_2005_TO_2023', 'add', 37.5, 'derived: 75% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Tourism Sector', NULL, 'Flood', 'FLOOD_EVENTS_1974_TO_2023', 'retire', NULL, NULL, 'superseded by FLOOD_EVENTS_1974_TO_2004 + FLOOD_EVENTS_2005_TO_2023'),
  ('Sabaragamuwa', 'Tourism Sector', NULL, 'Flood', 'THREE_DAY_CUMULATIVE_RAINFALL', 'add', 21, 'derived: 60% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Tourism Sector', NULL, 'Flood', 'VERY_WET_DAYS_95TH_PERCENTILE', 'add', 14, 'derived: 40% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Tourism Sector', NULL, 'Flood', 'VERY_WET_DAYS', 'retire', NULL, NULL, 'superseded by THREE_DAY_CUMULATIVE_RAINFALL + VERY_WET_DAYS_95TH_PERCENTILE'),
  ('Sabaragamuwa', 'Transportation Sector', NULL, 'Flood', 'FLOOD_EVENTS_1974_TO_2004', 'add', 12.5, 'derived: 25% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Transportation Sector', NULL, 'Flood', 'FLOOD_EVENTS_2005_TO_2023', 'add', 37.5, 'derived: 75% of retired FLOOD_EVENTS_1974_TO_2023 (50)', 'replaces FLOOD_EVENTS_1974_TO_2023'),
  ('Sabaragamuwa', 'Transportation Sector', NULL, 'Flood', 'FLOOD_EVENTS_1974_TO_2023', 'retire', NULL, NULL, 'superseded by FLOOD_EVENTS_1974_TO_2004 + FLOOD_EVENTS_2005_TO_2023'),
  ('Sabaragamuwa', 'Transportation Sector', NULL, 'Flood', 'THREE_DAY_CUMULATIVE_RAINFALL', 'add', 21, 'derived: 60% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Transportation Sector', NULL, 'Flood', 'VERY_WET_DAYS_95TH_PERCENTILE', 'add', 14, 'derived: 40% of retired VERY_WET_DAYS (35)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Transportation Sector', NULL, 'Flood', 'VERY_WET_DAYS', 'retire', NULL, NULL, 'superseded by THREE_DAY_CUMULATIVE_RAINFALL + VERY_WET_DAYS_95TH_PERCENTILE'),
  ('Sabaragamuwa', 'Transportation Sector', NULL, 'Landslide', 'THREE_DAY_CUMULATIVE_RAINFALL', 'add', 18, 'derived: 60% of retired VERY_WET_DAYS (30)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Transportation Sector', NULL, 'Landslide', 'VERY_WET_DAYS_95TH_PERCENTILE', 'add', 12, 'derived: 40% of retired VERY_WET_DAYS (30)', 'replaces VERY_WET_DAYS'),
  ('Sabaragamuwa', 'Transportation Sector', NULL, 'Landslide', 'VERY_WET_DAYS', 'retire', NULL, NULL, 'superseded by THREE_DAY_CUMULATIVE_RAINFALL + VERY_WET_DAYS_95TH_PERCENTILE');


DO $panel$
DECLARE
    s      RECORD;
    v_pid  BIGINT;
    v_prov SMALLINT;
    v_sec  BIGINT;
    v_sub  BIGINT;
    v_haz  BIGINT;
    v_user BIGINT;
    v_items JSONB;
    v_new  BIGINT;
    n_done INTEGER := 0;
BEGIN
    SELECT id INTO v_user FROM app_user
     WHERE email = 'panel-import@riskradar.local';
    IF v_user IS NULL THEN
        RAISE EXCEPTION 'the panel-import service account is missing - step 0 did not run';
    END IF;

    FOR s IN
        SELECT DISTINCT province, sector, subsector, hazard FROM panel_override
         ORDER BY 1, 2, 3, 4
    LOOP
        SELECT vp.id, vp.province_id, vp.sector_id, vp.subsector_id, vp.hazard_type_id
          INTO v_pid, v_prov, v_sec, v_sub, v_haz
          FROM vulnerability_profile vp
          JOIN province p     ON p.id  = vp.province_id
          JOIN sector   sec   ON sec.id = vp.sector_id
          LEFT JOIN subsector sub ON sub.id = vp.subsector_id
          JOIN hazard_type h  ON h.id  = vp.hazard_type_id
         WHERE vp.is_active
           AND p.name   = s.province
           AND sec.name = s.sector
           AND COALESCE(sub.name, '') = COALESCE(s.subsector, '')
           AND h.name   = s.hazard;

        IF v_pid IS NULL THEN
            RAISE EXCEPTION 'No active profile for % / % / % / %',
                s.province, s.sector, s.subsector, s.hazard;
        END IF;

        WITH ov AS (
            SELECT * FROM panel_override o
             WHERE o.province = s.province AND o.sector = s.sector
               AND COALESCE(o.subsector,'') = COALESCE(s.subsector,'')
               AND o.hazard = s.hazard
        ),
        cur AS (
            SELECT ic.code, pi.domain::text AS domain, pi.weight_pct,
                   pi.relationship::text AS relationship
              FROM profile_indicator pi
              JOIN indicator_catalog ic ON ic.id = pi.indicator_id
             WHERE pi.profile_id = v_pid
        ),
        added AS (
            SELECT o.code, ic.domain::text AS domain, o.weight_pct,
                   ic.direction::text AS relationship
              FROM ov o
              JOIN indicator_catalog ic ON ic.code = o.code
             WHERE o.action = 'add'
               AND NOT EXISTS (SELECT 1 FROM cur c WHERE c.code = o.code)
        ),
        merged AS (
            SELECT c.code, c.domain, c.relationship,
                   ow.action, COALESCE(ow.weight_pct, c.weight_pct) AS weight_pct,
                   COALESCE(ow.basis, ow.note) AS note
              FROM cur c
              LEFT JOIN ov ow ON ow.code = c.code
            UNION ALL
            SELECT a.code, a.domain, a.relationship,
                   'add', a.weight_pct,
                   (SELECT COALESCE(o2.basis, o2.note) FROM ov o2
                     WHERE o2.code = a.code AND o2.action = 'add' LIMIT 1)
              FROM added a
        ),
        typed AS (
            SELECT m.code, m.domain, m.relationship, m.note,
                   CASE
                     -- superseded: no weight, and the replacement is on the record
                     WHEN m.action = 'retire'                    THEN 'rejected'
                     -- a weight the panel itself entered
                     WHEN m.action = 'weight'                    THEN 'agreed'
                     -- a DERIVED split weight: counts, but is not an expert decision
                     WHEN m.action = 'add' AND m.weight_pct IS NOT NULL
                                                                 THEN 'contested'
                     -- no weight yet: not counted, not excluded
                     WHEN m.weight_pct IS NULL                   THEN 'proposed'
                     ELSE 'agreed'
                   END AS consensus,
                   CASE WHEN m.action = 'retire' THEN NULL ELSE m.weight_pct END
                       AS weight_pct
              FROM merged m
        )
        SELECT jsonb_agg(jsonb_build_object(
                   'code', t.code,
                   'domain', t.domain,
                   'weight_pct', t.weight_pct,
                   'relationship', t.relationship,
                   'consensus', t.consensus,
                   'consensus_note',
                       CASE WHEN t.consensus IN ('contested','rejected')
                            THEN COALESCE(t.note, 'recorded by the provincial panel review')
                       END))
          INTO v_items
          FROM typed t;

        v_new := save_profile_weights(
                     v_prov, v_sec, v_sub, v_haz, v_items, v_user, NULL,
                     s.province || ' panel review, returned 2026-09-13. '
                     || 'Weights marked contested are DERIVED splits of a retired '
                     || 'variable and await panel confirmation.');
        n_done := n_done + 1;
    END LOOP;

    RAISE NOTICE 're-saved % profiles from panel decisions', n_done;
END
$panel$;

COMMIT;
