#!/usr/bin/env python3
"""
D1 + D2 — generate the architecture and data-flow diagrams with Graphviz.

Same approach as generate_erd.py: the diagrams are generated, not hand-drawn,
so they can be re-rendered after a design change instead of quietly rotting.

These document the system AS BUILT (2026-07-29), not as originally imagined.
Node borders carry status:
    solid  = built and verified
    dashed = designed, not yet implemented

Writes: system-architecture.(dot|svg|png)
        data-flow.(dot|svg|png)

Usage:  python generate_diagrams.py
"""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))

# palette shared with the ERD so the whole design pack reads as one thing
C_USER   = "#7c5cbf"
C_FRONT  = "#1565c0"
C_API    = "#00695c"
C_STORE  = "#2e7d32"
C_AGENT  = "#5d4037"
C_INPUT  = "#c77400"
C_SPATIAL = "#00838f"
C_SCEN   = "#ad1457"
GREY     = "#616161"

FOOT = ("Solid border = built and verified   |   dashed = designed, not yet implemented"
        "\\nGenerated by design/architecture/generate_diagrams.py — do not hand-edit")


def node(name, label, colour, built=True, shape="box", extra=""):
    style = "rounded,filled" if shape == "box" else "filled"
    if not built:
        style += ",dashed"
    return (f'  {name} [label="{label}", shape={shape}, style="{style}", '
            f'fillcolor="{colour}18", color="{colour}", penwidth={2 if built else 1.4}, '
            f'fontcolor="#1c2b26"{extra}];')


# ---------------------------------------------------------------------------
# D1 — system architecture
# ---------------------------------------------------------------------------
def architecture():
    L = ['digraph ARCH {',
         '  rankdir=TB; splines=spline; nodesep=0.45; ranksep=0.85;',
         '  graph [fontname="Helvetica", fontsize=15, labelloc=t, '
         f'label="Risk Radar — System Architecture (D1)\\n'
         f'DS-division Climate Vulnerability Assessment, Sri Lanka   |   2026-07-29\\n\\n{FOOT}"];',
         '  node [fontname="Helvetica", fontsize=10.5, margin="0.18,0.12"];',
         '  edge [fontname="Helvetica", fontsize=9, color="#555555", arrowsize=0.75];']

    # ---- people ----
    L.append('  subgraph cluster_users {')
    L.append(f'    label="Users & roles (B4)"; fontcolor="{C_USER}"; color="{C_USER}"; '
             'style=rounded; fontsize=11;')
    L.append(node("u_officer", "Data Officer\\nprovincial data entry", C_USER, False))
    L.append(node("u_expert",  "Expert\\nknowledge-based values", C_USER, False))
    L.append(node("u_comm",    "General User\\n1–5 severity ratings", C_USER, False))
    L.append(node("u_admin",   "Administrator\\nusers, catalog, versions", C_USER, False))
    L.append(node("u_public",  "Public\\nread-only map, no login", C_USER, False))
    L.append('  }')

    # ---- inputs ----
    L.append('  subgraph cluster_in {')
    L.append(f'    label="Inputs"; fontcolor="{C_INPUT}"; color="{C_INPUT}"; style=rounded; fontsize=11;')
    L.append(node("i_wb", "243 Excel workbooks\\n2 period tabs × 330 DS rows\\n"
                          "reference-only WEIGHTS tab", C_INPUT))
    L.append(node("i_shp", "Official shapefiles\\nADM1 · ADM2 · ADM3 (330)\\nEPSG:4326", C_INPUT))
    L.append(node("i_panel", "Local expert panel\\nreviews OFFLINE →\\nrecorded as panel_note",
                  C_INPUT, True, "note"))
    L.append(node("i_docs", "Policy / adaptation\\ndocuments (A1)", C_INPUT, False))
    L.append('  }')

    # ---- frontend ----
    L.append('  subgraph cluster_fe {')
    L.append(f'    label="Frontend — Angular + TypeScript + OpenLayers (Stage 5)"; '
             f'fontcolor="{C_FRONT}"; color="{C_FRONT}"; style=rounded; fontsize=11;')
    L.append(node("f_map",   "Map dashboard (F2)\\nDS choropleth · track /\\nhazard / sector / SSP toggles", C_FRONT, False))
    L.append(node("f_imp",   "Import wizard (F3)\\nupload → confirm weights", C_FRONT, False))
    L.append(node("f_wts",   "Profile weights (F3)\\nedit any time · versioned", C_FRONT, False))
    L.append(node("f_fb",    "Expert + community\\nforms (F4)", C_FRONT, False))
    L.append(node("f_tool",  "Map toolbox (F6)\\ncalculate → review → commit", C_FRONT, False))
    L.append(node("f_chat",  "Agent chat (A3)", C_FRONT, False))
    L.append('  }')

    # ---- api ----
    L.append('  subgraph cluster_api {')
    L.append(f'    label="Backend — FastAPI (Phase 1)"; fontcolor="{C_API}"; color="{C_API}"; '
             'style=rounded; fontsize=11;')
    L.append(node("a_ing",  "B2  Catalog + ingestion\\nPOST /imports\\nreads WEIGHTS tab, validates _META", C_API, False))
    L.append(node("a_wts",  "B2  PUT /profiles/{scope}/weights\\nsave_profile_weights()", C_API, False))
    L.append(node("a_eng",  "B3  Normalisation +\\nvulnerability engine", C_API, False))
    L.append(node("a_auth", "B4  JWT auth + roles", C_API, False))
    L.append(node("a_ssp",  "B5  SSP scenarios +\\nimpact projection", C_API, False))
    L.append(node("a_geo",  "B6  GeoJSON map API", C_API, False))
    L.append(node("a_shp",  "B7  Spatial layer import", C_API, False))
    L.append(node("a_tool", "B8  Spatial toolbox\\n→ computation_result", C_API, False))
    L.append('  }')

    # ---- store ----
    L.append('  subgraph cluster_db {')
    L.append(f'    label="PostgreSQL 15 + PostGIS  (+ pgvector, optional)  — BUILT 2026-07-29"; '
             f'fontcolor="{C_STORE}"; color="{C_STORE}"; style=rounded; fontsize=11;')
    L.append(node("d_ref",  "Reference\\n9 provinces · 3 hazards\\n8 sectors · 12 subsectors\\n"
                            "330 DS divisions (geom)", C_STORE, True, "cylinder"))
    L.append(node("d_cat",  "indicator_catalog\\n174 variables\\n+ 269 aliases", C_STORE, True, "cylinder"))
    L.append(node("d_prof", "vulnerability_profile 243\\nprofile_indicator 3,664\\n"
                            "1,783 weights still NULL", C_STORE, True, "cylinder"))
    L.append(node("d_val",  "indicator_value\\nraw + normalised\\nsource: data|expert|community",
                  C_STORE, True, "cylinder"))
    L.append(node("d_res",  "vulnerability_result\\nimpact_projection\\nmonitoring_observation",
                  C_STORE, True, "cylinder"))
    L.append(node("d_sp",   "spatial_layer / feature\\ncomputation_job / result",
                  C_SPATIAL, True, "cylinder"))
    L.append(node("d_vec",  "agent_document\\nagent_embedding  vector(1024)",
                  C_AGENT, False, "cylinder"))
    # one row, declared INSIDE the cluster - at graph level it pulls the nodes
    # out and the cluster box stops rendering
    L.append('    { rank=same; d_ref; d_cat; d_prof; d_val; d_res; d_sp; d_vec; }')
    L.append('  }')

    # ---- agent ----
    L.append('  subgraph cluster_ag {')
    L.append(f'    label="AI agent layer — RAG (Phase 3)"; fontcolor="{C_AGENT}"; '
             f'color="{C_AGENT}"; style=rounded; fontsize=11;')
    L.append(node("g_emb", "A1  Embedding pipeline", C_AGENT, False))
    L.append(node("g_api", "A2  RAG endpoints\\n“impact? measures?”", C_AGENT, False))
    L.append(node("g_llm", "Self-hosted LLM\\n+ embedding model\\n(not yet chosen)", C_AGENT, False, "note"))
    L.append('  }')

    L.append(node("m_mon", "M1  Monitoring\\npredicted vs actual", C_SCEN, False))

    # ---- edges ----
    e = L.append
    e('  u_officer -> f_imp;  u_officer -> f_wts;')
    e('  u_expert  -> f_fb;   u_expert  -> f_chat;')
    e('  u_comm    -> f_fb;   u_public  -> f_map [label="no login"];')
    e('  u_admin   -> f_wts;  u_admin   -> f_tool;')
    e('  i_panel -> f_wts [style=dashed, label="sign-off\\nas panel_note"];')
    e('  i_wb  -> f_imp;')
    e('  i_shp -> a_shp;  i_docs -> g_emb;')

    e('  f_imp  -> a_ing;  f_wts -> a_wts;  f_fb -> a_ing;')
    e('  f_map  -> a_geo;  f_tool -> a_tool;  f_chat -> g_api;')
    e('  f_map  -> a_ssp [style=dashed];')
    e('  a_auth -> f_imp [style=dashed, label="role gates"];')

    e('  a_ing  -> d_val;  a_ing -> d_cat [label="alias resolve"];')
    e('  a_wts  -> d_prof [label="new version\\non every save"];')
    e('  a_eng  -> d_val [dir=back, label="reads normalised"];')
    e('  a_eng  -> d_prof [dir=back, label="weights"];')
    e('  a_eng  -> d_res;')
    e('  a_ssp  -> d_res;  a_geo -> d_ref [dir=back];  a_geo -> d_res [dir=back];')
    e('  a_shp  -> d_sp;   a_tool -> d_sp;')
    e('  a_tool -> d_val [label="commit only", style=dashed];')
    e('  g_emb  -> d_vec;  g_api -> d_vec [dir=back];  g_api -> g_llm;')
    e('  d_res  -> m_mon;  m_mon -> d_res [label="observed"];')
    L.append('}')
    return "\n".join(L)


# ---------------------------------------------------------------------------
# D2 — data flow through the vulnerability pipeline
# ---------------------------------------------------------------------------
def dataflow():
    L = ['digraph FLOW {',
         '  rankdir=LR; splines=spline; nodesep=0.32; ranksep=0.62;',
         '  graph [fontname="Helvetica", fontsize=15, labelloc=t, '
         f'label="Risk Radar — Vulnerability Data Flow (D2)\\n'
         f'raw value → normalisation → indices → vulnerability → projection → monitoring   |   2026-07-29'
         f'\\n\\n{FOOT}"];',
         '  node [fontname="Helvetica", fontsize=10.5, margin="0.18,0.12"];',
         '  edge [fontname="Helvetica", fontsize=9, color="#555555", arrowsize=0.75];']

    # sources
    L.append('  subgraph cluster_src {')
    L.append(f'    label="1 · Raw values — three tracks, one schema"; fontcolor="{C_INPUT}"; '
             f'color="{C_INPUT}"; style=rounded; fontsize=11;')
    L.append(node("s_xl",  "Excel import\\nsource = 'data'", C_INPUT, False))
    L.append(node("s_ex",  "Expert entry\\nsource = 'expert'", C_INPUT, False))
    L.append(node("s_co",  "Community rating\\nsource = 'community'", C_INPUT, False))
    L.append(node("s_tb",  "Spatial toolbox\\nderivation = 'computed'", C_SPATIAL, False))
    L.append('  }')

    L.append(node("v_batch", "import_batch\\nvalidates _META,\\nstructure, DS codes\\n"
                             "errors → JSONB", C_API, False))
    L.append(node("v_raw", "indicator_value.raw_value\\nnative units, never normalised\\n"
                           "year_start / year_end", C_STORE, True, "cylinder"))

    # rules
    L.append('  subgraph cluster_rules {')
    L.append(f'    label="2 · Period rules (A3, decided 2026-07-26)"; fontcolor="{GREY}"; '
             f'color="{GREY}"; style=rounded; fontsize=11;')
    L.append(node("r_agg", "period_aggregation\\n160 average (a typical year)\\n"
                           "11 fixed_window · 3 max", GREY, True, "note"))
    L.append(node("r_yr",  "iv_for_year()\\n2025 is in BOTH periods →\\nlatest period wins", GREY, True, "note"))
    L.append('  }')

    L.append(node("n_norm", "3 · Normalisation (B3)\\nserver-side, never in Excel\\n"
                            "minmax | zscore\\npooled | per_year | fixed\\n"
                            "→ [0,1]", C_API, False))

    L.append(node("w_prof", "4 · Weighting\\nprofile_indicator\\nper province × sector × hazard\\n"
                            "Σ = 100 per domain\\n+ raises / − lowers", C_STORE, True))
    L.append(node("w_gate", "v_profile_readiness\\nany weight NULL →\\nREFUSE to compute\\n"
                            "(1,783 of 3,664 today)", "#c0392b", True, "note"))

    L.append(node("x_haz", "hazard_index ∈ [0,1]", C_API, False))
    L.append(node("x_exp", "exposure_index ∈ [0,1]", C_API, False))
    L.append(node("x_vul", "vulnerability_index\\n= f(Exposure, Hazard)\\n"
                           "per DS division · sector × hazard", C_API, False))
    L.append(node("d_vr",  "vulnerability_result\\nprofile_id pins the exact\\nweights used → every\\n"
                           "score stays explainable", C_STORE, True, "cylinder"))

    L.append(node("p_ssp", "5 · SSP scenario (B5)\\nscenario_parameter\\nshifts inputs\\nSSP1..SSP5",
                  C_SCEN, False))
    L.append(node("p_imp", "impact_projection\\nper sector / subsector", C_SCEN, False))
    L.append(node("m_obs", "6 · monitoring_observation\\nactual observed outcome", C_SCEN, False))
    L.append(node("m_cmp", "M1  predicted vs actual\\n→ alerts, model feedback", C_SCEN, False))
    L.append(node("o_map", "vector tiles (MVT)\\n→ OpenLayers choropleth\\n3 tracks side by side", C_FRONT, False))

    e = L.append
    e('  s_xl -> v_batch;  s_ex -> v_raw;  s_co -> v_raw;')
    e('  s_tb -> v_raw [label="computation_job_id\\nrequired (CHECK)", style=dashed];')
    e('  v_batch -> v_raw;')
    e('  r_agg -> n_norm [style=dashed];  r_yr -> n_norm [style=dashed];')
    e('  v_raw -> n_norm;')
    e('  n_norm -> w_prof;')
    e('  w_gate -> w_prof [style=dashed, color="#c0392b"];')
    e('  w_prof -> x_haz [label="domain =\\nhazard"];')
    e('  w_prof -> x_exp [label="domain =\\nexposure"];')
    e('  x_haz -> x_vul;  x_exp -> x_vul;')
    e('  x_vul -> d_vr;')
    e('  d_vr -> o_map;')
    e('  d_vr -> p_ssp;  p_ssp -> p_imp;  p_imp -> m_cmp;')
    e('  m_obs -> m_cmp;')
    e('  m_cmp -> n_norm [style=dashed, label="feedback", constraint=false];')
    L.append('}')
    return "\n".join(L)


def render(name, dot):
    path = os.path.join(HERE, f"{name}.dot")
    open(path, "w", encoding="utf-8").write(dot)
    sizes = []
    for fmt in ("svg", "png"):
        out = os.path.join(HERE, f"{name}.{fmt}")
        r = subprocess.run(["dot", f"-T{fmt}", path, "-o", out],
                           capture_output=True, text=True)
        if r.returncode:
            print(f"  ! graphviz failed on {name}.{fmt}: {r.stderr[:300]}", file=sys.stderr)
            return False
        sizes.append(f"{fmt} {os.path.getsize(out):,}b")
    print(f"  {name:24s} {' | '.join(sizes)}")
    return True


def main():
    os.makedirs(HERE, exist_ok=True)
    ok = render("system-architecture", architecture())
    ok &= render("data-flow", dataflow())
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
