#!/usr/bin/env python3
"""
Generate Annex G — the requirements traceability matrix — from SRS.md itself.

IEEE 29148 asks for bidirectional traceability between requirements and the
artefacts that verify them. Maintaining that by hand guarantees it drifts out of
date the first time a requirement is added, so it is generated: the matrix is
derived from the requirement tables in the document it appears in.

Every FR and NFR gets a row carrying its section, its priority, the component
that implements it, and how it is to be verified. Verification methods are
assigned per section (see METHOD below) because they are a property of the kind
of requirement, not of the individual line.

Writes back into SRS.md between the two ANNEX-G marker comments.

Usage:  python generate_traceability.py [--check]
        --check exits non-zero if the matrix is stale, for use in a build.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "SRS.md")

BEGIN = "<!-- ANNEX-G:BEGIN generated by generate_traceability.py -->"
END = "<!-- ANNEX-G:END -->"

# section prefix -> (implementing component, verification method, note)
METHOD = {
    "6.1":  ("Catalogue service",      "Test",          "Automated against the seeded catalogue"),
    "6.2":  ("Import service",         "Test",          "Fixture workbooks, one per Annex E code"),
    "6.3":  ("Weighting service",      "Test",          "Includes negative tests: 99.999 rejected"),
    "6.4":  ("Computation engine",     "Test",          "Recomputation must be bit-identical (NFR-2)"),
    "6.5":  ("Map frontend",           "Demonstration", "Scripted browser run at each admin level"),
    "6.6":  ("Scenario engine",        "Test",          "Projection reproducible from stored adjustments"),
    "6.7":  ("Spatial toolbox",        "Test",          "Known-answer checks in EPSG:5235"),
    "6.8":  ("Assistant",              "Demonstration", "Includes the layer-unavailable path (FR-8.2b)"),
    "6.9":  ("Monitoring",             "Demonstration", ""),
    "6.10": ("Admin console",          "Demonstration", ""),
    "6.11": ("Migration job",          "Test",          "Idempotency: second run adds no rows"),
    "6.12": ("Risk engine",            "Test",          "Blocked on O-11 until asset layers load"),
    "6.13": ("Audit subsystem",        "Test",          "Append-only proven by attempted UPDATE/DELETE"),
    "6.14": ("API and OGC layer",      "Test",          "GetCapabilities parsed and schema-validated"),
    "6.15": ("Notification service",   "Demonstration", ""),
}

NFR_METHOD = {
    "NFR-1": ("Database",       "Inspection",    "Schema review: provenance columns NOT NULL"),
    "NFR-2": ("Computation",    "Test",          "Same inputs, same profile version, identical output"),
    "NFR-3": ("Tile service",   "Test",          "Load test at stated thresholds"),
    "NFR-4": ("API framework",  "Inspection",    "Default permission asserted in settings test"),
    "NFR-5": ("Database",       "Test",          "Negative tests in Annex C"),
    "NFR-6": ("Database",       "Test",          "No in-place update of a published result"),
    "NFR-7": ("Deployment",     "Demonstration", "Full install on one server, no external service"),
    "NFR-8": ("Frontend, data", "Inspection",    "Three locales present for all reference data"),
    "NFR-9": ("Frontend",       "Inspection",    "WCAG 2.1 AA audit"),
    "NFR-10": ("All layers",    "Test",          "No endpoint returns 0 for an absent value"),
    "NFR-11": ("Frontend",      "Inspection",    "Keyboard and screen-reader pass"),
    "NFR-12": ("Operations",    "Demonstration", "Restore exercised before handover, not assumed"),
    "NFR-13": ("Operations",    "Demonstration", ""),
    "NFR-14": ("Deployment",    "Test",          "Concurrency load test"),
    "NFR-15": ("Assistant",     "Test",          "Time to first token and to completion"),
    "NFR-16": ("Frontend",      "Demonstration", "360 px to 1920 px"),
    "NFR-17": ("Database",      "Inspection",    "Deletion path absent from API and interface"),
    "NFR-18": ("Storage",       "Inspection",    "Checksums recorded, bodies not in the database"),
}

ID_RE = re.compile(r"^\|\s*((?:FR|NFR)-[0-9]+(?:\.[0-9]+)?[a-z]?)\s*\|(.*?)\|\s*$")
HEAD_RE = re.compile(r"^###\s+(\d+\.\d+)\s+(.*)$")


def sort_key(rid):
    m = re.match(r"(FR|NFR)-(\d+)(?:\.(\d+))?([a-z]?)", rid)
    kind, major, minor, suffix = m.groups()
    return (0 if kind == "FR" else 1, int(major), int(minor or 0), suffix)


def collect(md):
    """Walk the document, tracking the current §x.y heading, and pull every
    requirement row out of the tables beneath it.

    The generated annex is stripped first. Without this the matrix reads its own
    rows on the second run, doubles every requirement, and reports itself stale
    forever.
    """
    md = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), "", md, flags=re.S)
    section, title, rows = None, None, []
    for line in md.split("\n"):
        h = HEAD_RE.match(line)
        if h:
            section, title = h.group(1), h.group(2).strip()
            continue
        m = ID_RE.match(line)
        if not m:
            continue
        rid, text = m.group(1), m.group(2).strip()
        # priority tag is inline in the requirement text
        pri = "Should" if "`(Should)`" in text else "Could" if "`(Could)`" in text else "Must"
        rows.append({"id": rid, "section": section, "title": title, "priority": pri})
    return rows


def build(rows):
    out = [BEGIN, "", "## Annex G — Requirements traceability",
           "",
           "Generated from the requirement tables in this document by",
           "`generate_traceability.py`. Re-run it after adding a requirement; do not",
           "edit this annex by hand.",
           "",
           "Verification methods follow IEEE 29148: **Test** (automated, repeatable),",
           "**Demonstration** (exercised against the running system), **Inspection**",
           "(code or configuration reviewed), **Analysis** (reasoned from design).",
           "", ""]

    frs = [r for r in rows if r["id"].startswith("FR-")]
    nfrs = [r for r in rows if r["id"].startswith("NFR-")]

    out += ["### Functional requirements", "",
            "| ID | Section | Priority | Implemented by | Verification | Note |",
            "|---|---|---|---|---|---|"]
    for r in sorted(frs, key=lambda x: sort_key(x["id"])):
        comp, meth, note = METHOD.get(r["section"], ("—", "Analysis", ""))
        out.append(f"| {r['id']} | §{r['section']} {r['title']} | {r['priority']} "
                   f"| {comp} | {meth} | {note} |")

    out += ["", "### Non-functional requirements", "",
            "| ID | Priority | Implemented by | Verification | Note |",
            "|---|---|---|---|---|"]
    for r in sorted(nfrs, key=lambda x: sort_key(x["id"])):
        base = re.match(r"(NFR-\d+)", r["id"]).group(1)
        comp, meth, note = NFR_METHOD.get(r["id"], NFR_METHOD.get(base,
                                          ("—", "Analysis", "")))
        out.append(f"| {r['id']} | {r['priority']} | {comp} | {meth} | {note} |")

    n_must = sum(1 for r in rows if r["priority"] == "Must")
    n_should = sum(1 for r in rows if r["priority"] == "Should")
    n_could = sum(1 for r in rows if r["priority"] == "Could")
    out += ["",
            f"**{len(rows)} requirements** — {len(frs)} functional, {len(nfrs)} "
            f"non-functional. **{n_must} Must · {n_should} Should · {n_could} Could.**",
            "",
            "Status is deliberately absent. Nothing in the application layer is built "
            "(§10), so a status column would read *not started* on every row and say "
            "less than this sentence does. It is added when implementation begins.",
            "", END]
    return "\n".join(out)


def main():
    md = open(SRC, encoding="utf-8").read()
    if BEGIN not in md or END not in md:
        print("markers not found in SRS.md", file=sys.stderr)
        return 1
    rows = collect(md)
    if not rows:
        print("no requirements found — did the table format change?", file=sys.stderr)
        return 1
    annex = build(rows)
    new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: annex,
                 md, flags=re.S)
    if "--check" in sys.argv:
        stale = new != md
        print("stale" if stale else "up to date")
        return 1 if stale else 0
    open(SRC, "w", encoding="utf-8").write(new)
    print(f"  Annex G: {len(rows)} requirements "
          f"({sum(1 for r in rows if r['id'].startswith('FR-'))} FR / "
          f"{sum(1 for r in rows if r['id'].startswith('NFR-'))} NFR)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
